# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-05-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200514_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
